title = "Elementary"
theme = "tract"
# disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://forensicanalysis.github.io/documentation"

[params]
description = "Tooling for forensic investigations."
icon_set = "ionicons"

[params.colors]
primary = "#ef5350"
secondary = "#37474f"
# red: ef5350 grey: 37474f

[markup.highlight]
style = "monokai"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Roboto Slab"
sizes = [400]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400]
type = "monospace"

[params.social.slack]
channel = "open-source-dfir"

[params.social.github]
repo = "forensicanalysis"

[[menu.main]]
name = "Documentation"
identifier = "docs"
url = "https://forensicanalysis.github.io/documentation/docs/"
weight = 1

[[menu.main]]
name = "Usage"
parent = "docs"
url = "https://forensicanalysis.github.io/documentation/docs/usage/"
weight = 2

[[menu.main]]
name = "Development"
parent = "docs"
url = "https://forensicanalysis.github.io/documentation/docs/development/"
weight = 4

# [[menu.main]]
# name = "Blog"
# identifier = "blog"
# url = "/blog"
# weight = 2
