title = "Elementary"
theme = "tract"
# disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "Tooling for forensic investigations."
icon_set = "ionicons"

[params.colors]
primary = "#c2185b" # c2185b
secondary = "#0277bd"

[markup.highlight]
style = "monokai"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Alata"
sizes = [400]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400]
type = "monospace"

# [params.social.twitter]
# handle = "jonas_plum"

[params.social.slack]
channel = "open-source-dfir"

[params.social.github]
repo = "forensicanalysis"

[[menu.main]]
name = "Documentation"
identifier = "docs"
url = "/docs"
weight = 1

# [[menu.main]]
# name = "Getting started"
# parent = "docs"
# url = "/docs/getting-started/"
# weight = 1

[[menu.main]]
name = "Usage"
parent = "docs"
url = "/docs/usage/"
weight = 2

# [[menu.main]]
# name = "Processing"
# parent = "docs"
# url = "/docs/processing/"
# weight = 3

[[menu.main]]
name = "Development"
parent = "docs"
url = "/docs/development/"
weight = 4

[[menu.main]]
name = "Blog"
identifier = "blog"
url = "/blog"
weight = 2
